Eliminate 500 internal server errors when configuring CLI Pod
When test scripts are run, when we get to the point where the Conjur
CLI Pod is being configured (client cert initialized and log into
Conjur), we see the following error:

```
Configuring Conjur CLI.
++++++++++++++++++++++++++++++++++++++
Waiting for 'kubectl exec conjur-cli-854cf5d95d-d7vgp -- bash -c "yes yes | conjur init -a cucumber -u https://conjur-oss.local-conjur.svc.cluster.local"' up to 300 s
error: Unable to retrieve certificate from conjur-oss.local-conjur.svc.cluster.local:443
command terminated with exit code 1
.error: Unable to retrieve certificate from conjur-oss.local-conjur.svc.cluster.local:443
command terminated with exit code 1
.Trust this certificate (yes/no): Success!
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Created new account 'cucumber'
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Logged in
error: 500 Internal Server Error
command terminated with exit code 1
``

This is an intermittent error. I don't know the root cause, but
executing the login inside a retry loop will fix the issue.